server:
  port: 8081

spring:
  application:
    name: springboot-elastsearch


#elasticsearch
elasticsearch:
  schema: http
  address: 172.28.116.239:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100
