datasource:
  url: localhost:3306/springboot-learn
spring:
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  type-aliases-package: com.zp.pojo
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名规范