spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  minio:
    access-key: minio
    secret-key: minio123456
    bucket-name: testminio
    url: http://127.0.0.1:19000
  thymeleaf:
    cache: false
server:
  port: 18081