spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      dirver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/read1
      username: root
      password: root
      dirver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/read2
      username: root
      password: root
      dirver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zp.entity