server:
  port: 8081
# 数据库连接

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest_springboot_cache
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# Redis 配置

redis:
  ## 数据库索引(默认为0)
  database: 0
  # host: 127.0.0.1
  host: 172.28.116.253
  port: 6379
  password:
  jedis:
    pool:
      max-active: 100 #连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      # spring.redis.pool.max-wait= -1
      max-wait: 100000

    # 连接超时时间（毫秒）
    timeout: 5000

#将themilef的默认缓存禁用，热加载生效
thymeleaf:
    cache: false

#mybatis的下划线转驼峰配置
configuration:
  map-underscore-to-camel-case: true

    #另外一种打印语句的方式
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#打印sql时的语句
logging:
  level:
    com:
      acong:
        dao: debug
  file: d:/logs/bsbdj.log